### ISSUE TITLE
[BUG] ncclient_call vs scrapli_netconf_call

### ISSUE THREAD

**Issue by gcasella** [dmulyalin/nornir-salt#11]
Hey @dmulyalin 

Have a weird one that I'm experiencing. 

I have a device that runs IPv6 only. It appears when I try to connect in using 3 different methods I get different symptoms / outcomes.

1. Using your ncclient_call
* This will fail for me 100% of the time with a ncclient rpc reply timeout doing 15 execution attempts.
```
[INFO    ] Nornir-proxy MAIN PID 47 starting task 'nornir_salt.plugins.tasks.ncclient_call'
[INFO    ] Running task 'nornir_salt.plugins.tasks.ncclient_call' with args {'source': 'running', 'call': 'get_config', 'connection_name': 'ncclient'} on 1 hosts
[INFO    ] nornir_salt:RetryRunner IPv6_ROUTER - connecting with creds retry
[INFO    ] nornir_salt:conn_open IPv6_ROUTER 'ncclient' connecting with primary connection parameters
[INFO    ] Connected (version 2.0, client OpenSSH_7.5)
[INFO    ] nornir_salt:conn_open IPv6_ROUTER 'ncclient' re-connecting with 'tacacs_account' connection parameters
[INFO    ] Connected (version 2.0, client OpenSSH_7.5)
[INFO    ] Auth banner: b"==========================\nAuthorized Access Only!!!\n========================\nWARNING\n\n"
[INFO    ] Authentication (password) successful!
[INFO    ] [host 2605:b100:1300:6157:5608:0000:0000:0001 session 0x7ff69c99a9e0] Sending:
<?xml version="1.0" encoding="UTF-8"?><nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><nc:capabilities><nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:base:1.1</nc:capability><nc:capability>urn:ietf:params:netconf:capability:writable-running:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:startup:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</nc:capability><nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:xpath:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:notification:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:interleave:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:with-defaults:1.0</nc:capability></nc:capabilities></nc:hello>]]>]]>
[INFO    ] [host 2605:b100:1300:6157:5608:0000:0000:0001 session 0x7ff69c99a9e0] Received message from host
[INFO    ] [host 2605:b100:1300:6157:5608:0000:0000:0001 session-id 12499] initialized: session-id=12499 | server_capabilities=<dict_keyiterator object at 0x7ff69c9c1d50>
[INFO    ] nornir_salt:RetryRunner IPv6_ROUTER - started connection: 'ncclient'
[INFO    ] nornir_salt:RetryRunner IPv6_ROUTER - running task 'nornir_salt.plugins.tasks.ncclient_call'
[INFO    ] [host 2605:b100:1300:6157:5608:0000:0000:0001 session-id 12499] Requesting 'GetConfig'
[INFO    ] [host 2605:b100:1300:6157:5608:0000:0000:0001 session-id 12499] Sending:
<?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:09c0342a-de66-42f0-a71e-6f6422f9a911"><nc:get-config><nc:source><nc:running/></nc:source></nc:get-config></nc:rpc>]]>]]>
[ERROR   ] Host 'IPv6_ROUTER': task 'get_config' failed with traceback:
Traceback (most recent call last):
  File "/opt/saltstack/salt/extras-3.10/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/opt/saltstack/salt/extras-3.10/nornir_salt/utils/yangdantic.py", line 47, in wrapper
    return self.function(*args, **kwargs)
  File "/opt/saltstack/salt/extras-3.10/nornir_salt/plugins/tasks/ncclient_call.py", line 343, in ncclient_call
    result = getattr(manager, call)(*args, **kwargs)
  File "/opt/saltstack/salt/extras-3.10/ncclient/manager.py", line 246, in execute
    return cls(self._session,
  File "/opt/saltstack/salt/extras-3.10/ncclient/operations/retrieve.py", line 166, in request
    return self._request(node)
  File "/opt/saltstack/salt/extras-3.10/ncclient/operations/rpc.py", line 381, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.
```

2. Using your scrapli_netconf_call
* This is successful 100% of the time out of 15 execution attempts.

3. Using raw ncclient python library
* Using this basic code below is successful 100% of the time executing 15 times.
```
#!/usr/bin/env python
import os
import sys
import time
import logging

from ncclient import manager

from ncclient.operations import RaiseMode
logging.getLogger('__main__').setLevel('WARNING')
logging.getLogger('ncclient').setLevel('WARNING')
def connect(host, port, user, password):
    for _ in range(15):
        print(f"Run #{_}")
        time.sleep(3)
        try:
            with manager.connect(host=host, port=830,
                                    username=user, 
                                    password=password, 
                                    hostkey_verify=False,
                                    timeout=10,
                                    device_params={'name': 'junos'}) as m:
                    m.raise_mode = RaiseMode.ERRORS
                    c = m.get_config(source='running')
                    if c:
                        print("completed")    # # configuration as a string
        except Exception as exp:
            print("failed")

if __name__ == '__main__':
    LOG_FORMAT = '%(asctime)s %(levelname)s %(filename)s:%(lineno)d %(message)s'
    logging.basicConfig(stream=sys.stdout, level=logging.INFO, format=LOG_FORMAT)

    connect('2605:b100:1300:6157:5608:0000:0000:0001', '830', "user", "password")
```

**Comment by gcasella** [comment]
Not an issue with any package. I found the source problem it was related to something on the network.
