### ISSUE TITLE
scrapli_netconf_call fails when using QueueRunner

### ISSUE THREAD

**Issue by gcasella** [dmulyalin/nornir-salt#2]
When trying to use scrapli_netconf_call while using the QueueRunner fails to work. 

If i change my runner back to RetryRunner connections work as expected.
Below is the traceback when using QueueRunner;
```
get_config:
            Traceback (most recent call last):
              File "/opt/salt/venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
                r = self.task(self, **self.params)
              File "/opt/salt/venv/lib/python3.9/site-packages/nornir_salt/plugins/tasks/scrapli_netconf_call.py", line 232, in scrapli_netconf_call
                result = getattr(conn, call)(*args, **kwargs)
            TypeError: get_config() got an unexpected keyword argument 'connection_name'
```

**Comment by dmulyalin** [comment]
This should be fixed starting with 0.10.1 release.
