### ISSUE TITLE
OSError: handle is closed

### ISSUE THREAD

**Issue by abhi1693** [dmulyalin/nornir-salt#4]
I sometimes get the below error and the only recovery is to kill the proxy process and start again.

```
The minion function caused an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/salt/metaproxy/proxy.py", line 482, in thread_return
    return_data = minion_instance.executors[fname](
  File "/usr/local/lib/python3.8/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nornir_salt/utils/yangdantic.py", line 47, in wrapper
    return self.function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt_nornir/modules/nornir_proxy_execution_module.py", line 1206, in cli
    result = __proxy__["nornir.execute_job"](
  File "/usr/local/lib/python3.8/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/salt_nornir/proxy/nornir_proxy_module.py", line 1766, in execute_job
    res = nornir_data["res_queue"].get(block=True, timeout=0.1)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed

```

**Comment by dmulyalin** [comment]
This might be a known issue with running out of file descripto (FD) limits https://salt-nornir.readthedocs.io/en/latest/Overview.html#nornir-process-watchdog-or-known-issues - could you run nr.nornir stats for process that stuck and check main_process_fd_count and main_process_fd_limit counters to confirm. 

Also, could you share logs for affected proxy minion of warning error and critical levels from /var/log/salt/proxy file - wondering if watchdog process logs any useful info.

**Comment by abhi1693** [comment]
I've checked a few more times and came to the conclusion that the issue arises only when the call to the proxy happens while it is getting refreshed.

**Comment by dmulyalin** [comment]
Ok, I'll have a look at introducing something like `nr.nornir refresh inventory_only=True` feature to only re-instantiate workers in graceful manner by giving time for current running commands to complete following with inventory refresh for all workers. Also will try to improve exception handling by child processes to give better message back to user if queues gets destroyed by parent process on refresh.

**Comment by dmulyalin** [comment]
Released nornir-salt /salt-nornir 0.13.0, it has above implemented - added `nr.nornir refresh workers_only=True` feature and improved exception handling when doing jobs during hard refresh. 

Was wondering if you can share some insight on how automated discovery implemented in your case using salt-nornir proxy minions, was thinking of adding `nr.discovery` runner or engine SaltStack module to discover new devices on demand, on-event or on schedule. If you cannot share details here, might want to consider dropping me an email or reaching out on [networktocode slack](http://slack.networktocode.com/) dm

**Comment by abhi1693** [comment]
Could you share your ntc slack username? I'm unable to find you

**Comment by dmulyalin** [comment]
Oh, yeah, sorry, it's apraksim

**Comment by abhi1693** [comment]
Closing this as it's working as expected
